name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Deploy to Tomcat Server
        env:
          TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
          TOMCAT_URL: 'https://kiwi-celestial-unadvised.ngrok-free.dev/manager/text'
        run: |
          mvn clean package tomcat:redeploy \
            -Dmaven.tomcat.url=$TOMCAT_URL \
            -Dmaven.tomcat.username=$TOMCAT_USERNAME \
            -Dmaven.tomcat.password=$TOMCAT_PASSWORD \
            -DskipTests \
            -f ./pom.xml
